/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Alexis Javier Roman
 */
import figurasgeometricas.*;
import javax.swing.JOptionPane;
public class MenuSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form MenuSeleccion
     */
    public MenuSeleccion() {
        initComponents();
    }
    
    private void desbloquearbtn(){
        if ((rbtnRectangulo.isSelected() || rbtnTriangulo.isSelected()|| rbtnRomboide.isSelected()) && !textBase.getText().isEmpty() && !textAltura.getText().isEmpty()){
            btnAñadir.setEnabled(true);
        }
        else{
            btnAñadir.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnTriangulo = new javax.swing.JRadioButton();
        rbtnRectangulo = new javax.swing.JRadioButton();
        rbtnRomboide = new javax.swing.JRadioButton();
        textBase = new javax.swing.JTextField();
        textAltura = new javax.swing.JTextField();
        btnMostrarTriangulo = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbtnTriangulo.setText("Triangulo Equilatero");
        rbtnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTrianguloActionPerformed(evt);
            }
        });
        rbtnTriangulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbtnTrianguloKeyReleased(evt);
            }
        });

        rbtnRectangulo.setText("Rectangulo");
        rbtnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRectanguloActionPerformed(evt);
            }
        });
        rbtnRectangulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbtnRectanguloKeyReleased(evt);
            }
        });

        rbtnRomboide.setText("Romboide");
        rbtnRomboide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRomboideActionPerformed(evt);
            }
        });

        textBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBaseActionPerformed(evt);
            }
        });
        textBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textBaseKeyReleased(evt);
            }
        });

        textAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlturaActionPerformed(evt);
            }
        });
        textAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textAlturaKeyReleased(evt);
            }
        });

        btnMostrarTriangulo.setText("Mostrar Figuras");
        btnMostrarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTrianguloActionPerformed(evt);
            }
        });

        btnAñadir.setText("Añadir");
        btnAñadir.setEnabled(false);
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        jLabel1.setText("Base");

        jLabel2.setText("Altura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnRomboide)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbtnTriangulo)
                        .addGap(62, 62, 62)
                        .addComponent(rbtnRectangulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textBase, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnMostrarTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTriangulo)
                    .addComponent(rbtnRectangulo)
                    .addComponent(rbtnRomboide))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnMostrarTriangulo))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTrianguloActionPerformed
        rbtnRectangulo.setSelected(false);
        rbtnRomboide.setSelected(false);
        desbloquearbtn();
    }//GEN-LAST:event_rbtnTrianguloActionPerformed

    private void textAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlturaActionPerformed

    private void rbtnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRectanguloActionPerformed
        rbtnTriangulo.setSelected(false);
        rbtnRomboide.setSelected(false);
        desbloquearbtn();// TODO add your handling code here:
    }//GEN-LAST:event_rbtnRectanguloActionPerformed

    private void rbtnRomboideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRomboideActionPerformed
        rbtnRectangulo.setSelected(false);
        rbtnTriangulo.setSelected(false);
        desbloquearbtn();// TODO add your handling code here:
    }//GEN-LAST:event_rbtnRomboideActionPerformed

    private void textBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBaseActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        
        double auxbase=Double.parseDouble(textBase.getText());
        double auxaltu=Double.parseDouble(textAltura.getText());
        
        if (rbtnTriangulo.isSelected()){
            Figurasgeometricas.Figuras.add(new Triangulo(auxbase, auxaltu)); 
        }
        else if (rbtnRectangulo.isSelected()){
            Figurasgeometricas.Figuras.add(new Rectangulo(auxbase, auxaltu));
        }
        else{
            Figurasgeometricas.Figuras.add(new Romboide(auxbase, auxaltu));
        }
        
        JOptionPane.showMessageDialog(null, "¡¡¡¡ La figura se agrego con exito !!!!");
        
        rbtnTriangulo.setSelected(false);
        rbtnRectangulo.setSelected(false);
        rbtnRomboide.setSelected(false);
        textBase.setText("");
        textAltura.setText(""); 
        btnAñadir.setEnabled(false);
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void rbtnTrianguloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnTrianguloKeyReleased
// TODO add your handling code here:
    }//GEN-LAST:event_rbtnTrianguloKeyReleased

    private void rbtnRectanguloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnRectanguloKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRectanguloKeyReleased

    private void textBaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBaseKeyReleased
        desbloquearbtn();        // TODO add your handling code here:
    }//GEN-LAST:event_textBaseKeyReleased

    private void textAlturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAlturaKeyReleased
        desbloquearbtn();        // TODO add your handling code here:
    }//GEN-LAST:event_textAlturaKeyReleased

    private void btnMostrarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTrianguloActionPerformed
        MostrarFiguras Mostrar = new MostrarFiguras();
        Mostrar.setVisible(true);
        Mostrar.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnMostrarTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtnRectangulo;
    private javax.swing.JRadioButton rbtnRomboide;
    private javax.swing.JRadioButton rbtnTriangulo;
    private javax.swing.JTextField textAltura;
    private javax.swing.JTextField textBase;
    // End of variables declaration//GEN-END:variables
}
